# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85294de204c622d7ee2917d53a71f2b6611fd4fdd47d74bbc24d97b49bda7647b8af03c5453ed77c63b1a68612bf589125566e05701f4390a31ad4b525117201

test:
  secret_key_base: ef930366ec28da1a084b8eb6863a6322331436d91be1becb7919be6a65f68a52569abfe55a0edab181ce1e556654ed8e5ea53457c3252cabaa7d1e22d45c709c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
